version: '3.8'
services:
  code-executor:
    build: .
    ports:
      - "4000:4000"
    environment:
      DB_HOST: host.docker.internal  
      DB_USER: root
      DB_PASS: 1234
      DB_NAME: CAPKATON